package com.example.util

object LanguageTranslator {
    private val translations = mapOf(
        "en" to mapOf(
            "home" to "Home",
            "services" to "Services",
            "portfolio" to "Portfolio",
            "store" to "Store",
            "reviews" to "Reviews",
            "contact" to "Contact",
            "chatbot" to "AI Chatbot",
            "admin" to "Admin Panel",
            "tagline" to "Digital Expertise Hub",
            "hero_title" to "Hey, I'm Abhiraj Kumar",
            "hero_desc" to "I build enterprise-grade software architectures, native mobile applications, premium web platforms, and automated AI workflows. Let's transform your vision into dynamic reality.",
            "hire_me" to "Hire Me",
            "buy_now" to "Buy Now",
            "add_to_wishlist" to "Wishlist",
            "checkout" to "Secure Checkout",
            "ratings" to "Customer Reviews",
            "faq" to "Frequently Asked Questions",
            "contact_us" to "Get In Touch",
            "submit" to "Submit Project Request",
            "whatsapp_chat" to "WhatsApp",
            "telegram_chat" to "Telegram",
            "active_orders" to "Orders Delivered",
            "skills" to "Professional Skillset",
            "starting_at" to "Starting from",
            "delivery" to "Delivery:",
            "days" to "Days",
            "digital_products" to "Digital Downloads",
            "search_products" to "Search products...",
            "all" to "All",
            "filter" to "Filter",
            "sort_by" to "Sort By",
            "rating" to "Rating",
            "price_low_high" to "Price: Low to High",
            "price_high_low" to "Price: High to Low",
            "checkout_instructions" to "Secure Payment Portal",
            "transaction_id" to "Transaction ID",
            "payment_screenshot" to "Upload Screenshot",
            "place_order" to "Verify & Submit Order",
            "name" to "Your Name",
            "email" to "Email Address",
            "phone" to "Phone Number",
            "project_desc" to "Project Description",
            "budget" to "Project Budget",
            "attachment" to "Attach Blueprint/Requirements",
            "success" to "Success!",
            "message_sent" to "Your message has been sent successfully. Abhiraj will contact you shortly!",
            "order_placed" to "Your payment info has been submitted for manual verification. Downloads will unlock once approved!",
            "admin_dashboard" to "Admin Dashboard",
            "total_revenue" to "Total Revenue",
            "total_orders" to "Total Orders",
            "products" to "Products",
            "messages" to "Messages",
            "settings" to "Settings",
            "logout" to "Logout",
            "login_title" to "Admin Login",
            "chatbot_placeholder" to "Ask me about Abhiraj's services, store, or portfolio...",
            "send" to "Send",
            "languages" to "Languages",
            "dark_mode" to "Dark Theme"
        ),
        "hi" to mapOf(
            "home" to "मुख्य पृष्ठ",
            "services" to "सेवाएं",
            "portfolio" to "पोर्टफोलियो",
            "store" to "दुकान",
            "reviews" to "समीक्षाएं",
            "contact" to "संपर्क करें",
            "chatbot" to "एआई चैटबॉट",
            "admin" to "एडमिन पैनल",
            "tagline" to "डिजिटल विशेषज्ञता हब",
            "hero_title" to "नमस्ते, मैं अभिराज कुमार हूँ",
            "hero_desc" to "मैं एंटरप्राइज-ग्रेड सॉफ्टवेयर आर्किटेक्चर, नेटिव मोबाइल एप्लीकेशन, प्रीमियम वेब प्लेटफॉर्म और ऑटोमेटेड एआई वर्कफ्लो बनाता हूँ। आइए आपकी दृष्टि को गतिशील वास्तविकता में बदलें।",
            "hire_me" to "हायर करें",
            "buy_now" to "अभी खरीदें",
            "add_to_wishlist" to "विशलिस्ट",
            "checkout" to "सुरक्षित भुगतान",
            "ratings" to "ग्राहक समीक्षाएं",
            "faq" to "अक्सर पूछे जाने वाले प्रश्न",
            "contact_us" to "संपर्क स्थापित करें",
            "submit" to "प्रोजेक्ट अनुरोध भेजें",
            "whatsapp_chat" to "व्हाट्सएप",
            "telegram_chat" to "टेलीग्राम",
            "active_orders" to "ऑर्डर डिलीवर किए",
            "skills" to "व्यावसायिक कौशल",
            "starting_at" to "शुरुआती कीमत",
            "delivery" to "डिलीवरी का समय:",
            "days" to "दिन",
            "digital_products" to "डिजिटल डाउनलोड",
            "search_products" to "उत्पाद खोजें...",
            "all" to "सभी",
            "filter" to "फिल्टर",
            "sort_by" to "क्रमबद्ध करें",
            "rating" to "रेटिंग",
            "price_low_high" to "कीमत: कम से अधिक",
            "price_high_low" to "कीमत: अधिक से कम",
            "checkout_instructions" to "सुरक्षित भुगतान पोर्टल",
            "transaction_id" to "लेन-देन (UPI) आईडी",
            "payment_screenshot" to "स्क्रीनशॉट अपलोड करें",
            "place_order" to "भुगतान सत्यापित करें",
            "name" to "आपका नाम",
            "email" to "ईमेल पता",
            "phone" to "फ़ोन नंबर",
            "project_desc" to "प्रोजेक्ट का विवरण",
            "budget" to "प्रोजेक्ट बजट",
            "attachment" to "फाइल/ब्लूप्रिंट जोड़ें",
            "success" to "सफलता!",
            "message_sent" to "आपका संदेश सफलतापूर्वक भेज दिया गया है। अभिराज जल्द ही आपसे संपर्क करेंगे!",
            "order_placed" to "आपकी भुगतान जानकारी सत्यापन के लिए भेज दी गई है। स्वीकृति के बाद डाउनलोड लिंक अनलॉक हो जाएगा!",
            "admin_dashboard" to "एडमिन डैशबोर्ड",
            "total_revenue" to "कुल राजस्व",
            "total_orders" to "कुल ऑर्डर्स",
            "products" to "उत्पाद",
            "messages" to "संदेश",
            "settings" to "सेटिंग्स",
            "logout" to "लॉगआउट",
            "login_title" to "एडमिन लॉगिन",
            "chatbot_placeholder" to "अभिराज की सेवाओं, दुकान या पोर्टफोलियो के बारे में पूछें...",
            "send" to "भेजें",
            "languages" to "भाषाएं",
            "dark_mode" to "डार्क थीम"
        ),
        "hinglish" to mapOf(
            "home" to "Home",
            "services" to "Services",
            "portfolio" to "Portfolio",
            "store" to "Store",
            "reviews" to "Reviews",
            "contact" to "Contact Kare",
            "chatbot" to "AI Chatbot",
            "admin" to "Admin Panel",
            "tagline" to "Digital Expertise Hub",
            "hero_title" to "Namaste, Main Abhiraj Kumar hoon",
            "hero_desc" to "Main high-quality software, mobile apps, premium websites aur powerful AI chatbots banata hoon. Apne business ko next level par le jaane ke liye mujhe hire kare.",
            "hire_me" to "Hire Kare",
            "buy_now" to "Abhi Kharide",
            "add_to_wishlist" to "Wishlist",
            "checkout" to "Safe Checkout",
            "ratings" to "Client Reviews",
            "faq" to "FAQs Poochhe",
            "contact_us" to "Safar Shuru Kare",
            "submit" to "Project Details Bheje",
            "whatsapp_chat" to "WhatsApp",
            "telegram_chat" to "Telegram",
            "active_orders" to "Orders Delivered",
            "skills" to "Skills Aur Expertise",
            "starting_at" to "Starting Price",
            "delivery" to "Delivery:",
            "days" to "Days",
            "digital_products" to "Digital Downloads",
            "search_products" to "Products search kare...",
            "all" to "Sab",
            "filter" to "Filter",
            "sort_by" to "Sort Kare",
            "rating" to "Rating",
            "price_low_high" to "Price: Low se High",
            "price_high_low" to "Price: High se Low",
            "checkout_instructions" to "Secure Payment Portal",
            "transaction_id" to "Transaction ID dalo",
            "payment_screenshot" to "Screenshot Upload Karo",
            "place_order" to "Order Submit Kare",
            "name" to "Aapka Name",
            "email" to "Email ID",
            "phone" to "Phone Number",
            "project_desc" to "Project ki Details",
            "budget" to "Budget Kitna Hai",
            "attachment" to "Requirements File Attach Kare",
            "success" to "Safar Safal!",
            "message_sent" to "Aapka message submit ho gaya hai. Abhiraj aapse jaldi contact karega!",
            "order_placed" to "Payment details check ho rahi hai. Verified hote hi download unlock ho jayega!",
            "admin_dashboard" to "Admin Dashboard",
            "total_revenue" to "Total Kamai",
            "total_orders" to "Total Orders",
            "products" to "Products",
            "messages" to "Messages",
            "settings" to "Settings",
            "logout" to "Log out",
            "login_title" to "Admin Login",
            "chatbot_placeholder" to "Services, store ya orders ke bare mein poochho...",
            "send" to "Send",
            "languages" to "Bhasha",
            "dark_mode" to "Dark Mode"
        )
    )

    fun translate(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
